---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The Linux Foundation

name: voltctl release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    # Only invoked on release tag pushes
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Create GitHub release
        # yamllint disable-line rule:line-length
        uses: opencord/shared-workflows/.github/actions/github-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-targets: "release"
          artifact-glob: "release/*"
